### ISSUE TITLE
Configurer pipeline de déploiement 

### ISSUE THREAD

**Issue by FChapeau** [terra-arcana/terra-arcana#10]
Configurer un serveur Jenkins, un environnement de staging et un environnement de production pour le site et automatiser le tout.

**Comment by FChapeau** [comment]
J'ai commencé le ci. J'ai un serveur Jenkins qui fonctionne et est hébergé chez moi. Aucun script n'est configuré. 

Pour le moment, jopte pour un déploiement utilisant Docker pour standardiser le déploiement à travers les environnements. L'idée est que Jenkins va télécharger la source, rouler les tests et si ça passe, mettre à jour le Container et le déployer dans l'environnement approprié.

**Comment by FChapeau** [comment]
Le Jenkins est fonctionnel pour l'exécution automatique des tests sur la branche `development`. Au moment d'un push sur la branche, le serveur build la nouvelle version du site en development.

- [ ] Déployer automatiquement la nouvelle version en staging
- [ ] Tester automatiquement la nouvelle version du Master
- [ ] Déployer automatiquement la nouvelle version en Production

**Comment by ferdbold** [comment]
@FChapeau Ça avance?

**Comment by FChapeau** [comment]
Le container docker build avec succès. Par contre, Webpack indique des erreurs à presque toutes ses tâches du type "promise not defined". À investiguer.

Il faut tester le container Wordpress avec un container MySQL linké.

**Comment by ferdbold** [comment]
:metal:

**Comment by FChapeau** [comment]
Après beaucoup de douleur et de travail, le container build avec succès et l'application démarre avec la version présente sur la branche CI. Il reste à automatiser tout le processus, mais le gros du travail de déploiment est à 90% complété.

**Comment by FChapeau** [comment]
Le site se déploie automatiquement depuis le code sur GitHub grâce à Jenkins.
